trigger:
  branches:
    include:
    - master
  tags:
    include: ['*']

name:  $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]
  REPOSITORY_NAME: $(Build.Repository.Name)
  COMMIT_TAG: $(git log --format=%h -1)

steps:
- script: |
    curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
    sudo apt update
    sudo apt install p7zip-full haveged
    sudo dpkg -i pacman.deb
    sudo dkp-pacman -Sy
    sudo dkp-pacman -S nds-dev --noconfirm
  displayName: 'Setup environment'

- script: |
    echo $(TRAVIS_COMMIT)
    echo $(COMMIT_TAG)
    echo $(BUILD_SOURCEVERSION)
  displayName: 'Echo Variables'
  
- script: |
    export DEVKITPRO="/opt/devkitpro"
    export DEVKITARM="/opt/devkitpro/devkitARM"
    chmod +x make_cia
    make
    export COMMIT_TAG="$(git log --format=%h -1)"
    export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
    7z a Relaunch.7z Relaunch/
    cp Relaunch.7z $(Build.ArtifactStagingDirectory)/Relaunch.7z
    ls
    echo '##vso[task.setvariable variable=COMMIT_TAG]'$(git log --format=%h -1)
    echo '##vso[task.setvariable variable=COMMIT_MESSAGE]'$(git log --pretty=format:"%an - %s" -1)
  displayName: 'Build Relaunch'

- task: GitHubRelease@0
  displayName: "Release to Universal-Team/Relaunch"
  condition: startsWith(variables['Build.SourceBranchName'], 'v')
  inputs:
    gitHubConnection: TWLBot
    repositoryName: Universal-Team/Relaunch
    action: edit
    target: '$(Build.SourceVersion)'
    tag: $(Build.SourceBranchName)
    assets: '$(Build.ArtifactStagingDirectory)/**/*'

- script: |
    curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-azure.sh
    chmod +x send.sh
    ./send.sh success $WEBHOOK_URL
  condition: succeeded()
  displayName: "Send success webhook"
- script: |
    curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-azure.sh
    chmod +x send.sh
    ./send.sh failure $WEBHOOK_URL
  condition: failed()
  displayName: "Send failure webhook"
