name: Relaunch Binary Compilation

on:
  push:
    branches:
    - master
    - release/*
    tags:
      - v*

jobs:
  buildApplet:
    name: Build Relaunch
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set all variables
      id: variablesSetSet
      run: node ./get-metadata.js
    - name: Install devkit(Pro/ARM), libnds, and p7zip
      run: |
       curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
       sudo apt update
       sudo apt install p7zip-full haveged
       sudo dpkg -i pacman.deb
       sudo dkp-pacman -Sy
       sudo dkp-pacman -S nds-dev --noconfirm
    - name: make
      run: |
        chmod +x make_cia
        make
        7z a Relaunch.7z Relaunch/
    - name: Commit to Universal-Team/extras
      id: commit_to_extras
      run: |
        git config --global user.email "flamekat54@aol.com"
        git config --global user.name "TWLBot"
        git clone --depth 1 https://${{ secrets.BOT_TOKEN }}@github.com/Universal-Team/extras.git
        cd extras/builds/Relaunch/
        cp ../../../Relaunch.7z Relaunch.7z
        git stage .
        git commit -m "Relaunch | $COMMIT_TAG"
        git push origin master
    - name: webhook for broke build lmfao
      id: failed_Webhook
      if: failure() # trash broke, go fix it
      run: |
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-ghactions.sh
         sudo chmod +x send.sh
         ./send.sh failure ${{ secrets.WEBHOOK_URL }}
    - name: it work send webhook for success
      id: success_Webhook
      if: success() # it worked yay
      run: |
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-ghactions.sh
         sudo chmod +x send.sh
         ./send.sh success ${{ secrets.WEBHOOK_URL }}
    - uses: actions/upload-artifact@master
      with:
        name: Relaunch-${{ github.sha }}
        path: Relaunch/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Relaunch | $COMMIT_TAG
          draft: false
          prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Relaunch.7z
          asset_name: Relaunch.7z
          asset_content_type: application/zip
