name: Relaunch Binary Compilation

on:
  push:
    branches:
    - master
    - release/*
    tags:
      - v*           # Push events to tags beginning with "v"

jobs:
  buildApplet:
    name: Build Relaunch
    runs-on: ubuntu-16.04 # Operating System to use, in this case i used ubuntu 16.04

    steps:
    - uses: actions/checkout@v1 # idk what this does
    - name: install dkP # Name of the script, it can be anything
      run: | # run the lines below
       cd .github/workflows
       sudo chmod +x ./configure
       ./configure 
    - name: make
      env:
       COMMIT_TAG: $(git log --format=%h -1) # idk what i did here ngl
       CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)] # idk if that will work here, no harm in trying
      run: |
        export DEVKITPRO="/opt/devkitpro"
        export DEVKITARM="/opt/devkitpro/devkitARM"
        chmod +x make_cia
        make
        7z a Relaunch.7z Relaunch/
        ls
        export COMMIT_TAG="$(git log --format=%h -1)"
        export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
        git config --global user.email "flamekat54@aol.com"
        git config --global user.name "TWLBot"
        git clone --depth 1 https://${{ secrets.BOT_TOKEN }}@github.com/Universal-Team/extras.git
        cd extras/builds/Relaunch/
        cp ../../../Relaunch.7z Relaunch.7z
        git stage .
        git commit -m "Relaunch | $COMMIT_TAG"
        git push origin master
    - name: webhook for broke build lmfao
      if: failure() # trash broke, go fix it
      env:
        CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)] # idk if that will work here, no harm in trying
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-ghactions.sh
         sudo chmod +x send.sh
         ./send.sh failure $WEBHOOK_URL
    - name: it work send webhook for success
      if: success() # it worked yay
      env:
        CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)] # idk if that will work here, no harm in trying
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-ghactions.sh
         sudo chmod +x send.sh
         ./send.sh success $WEBHOOK_URL
    - uses: actions/upload-artifact@master
      with:
        name: Relaunch-${{ github.sha }}
        path: Relaunch/
