name: Relaunch Binary Compilation

on:
  push:
    branches:
    - master
    - release/*
    tags:
      - v*           # Push events to tags beginning with "v"

jobs:
  buildApplet:
    name: Build Relaunch
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: install dkP
      run: |
       cd .github/workflows
       sudo chmod +x ./configure
       ./configure
    - name: make
      env:
       COMMIT_TAG: $(git log --format=%h -1)
       BUILD_SOURCEVERSION: ${{ placeholder }}
       CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]
      run: |
        export DEVKITPRO="/opt/devkitpro"
        export DEVKITARM="/opt/devkitpro/devkitARM"
        chmod +x make_cia
        make
        export INPUT_COMMIT_TAG="$(git log --format=%h -1)"
        export INPUT_COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
        7z a Relaunch.7z Relaunch/
        ls
    - name: it failed send the broke webhook
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      if: failure()
      run: |
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-azure.sh
         chmod +x send.sh
         ./send.sh failure INPUT_WEBHOOK_URL
    - name: it did not fail send the not broke webhook
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      if: success()
      run: |
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-azure.sh
         chmod +x send.sh
         ./send.sh success INPUT_$WEBHOOK_URL
