name: Relaunch Nightly Builds

on:
  push:
    branches:
    - master
    - release/*

jobs:
  buildApplet:
    name: Build Relaunch
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
       cd .github/workflows
       sudo chmod +x ./configure
       ./configure
    - name: make
      run: |
        echo $(TRAVIS_COMMIT)
        echo $(COMMIT_TAG)
        echo $(BUILD_SOURCEVERSION)
        export DEVKITPRO="/opt/devkitpro"
        export DEVKITARM="/opt/devkitpro/devkitARM"
        chmod +x make_cia
        make
        export COMMIT_TAG="$(git log --format=%h -1)"
        export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
        7z a Relaunch.7z Relaunch/
        ls
